[package]
name = "diffdirs_nvim"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
strip = "debuginfo"

[dependencies]
nvim-oxi = { version = "0.5", features = ["neovim-0-10"] }
walkdir = "2.5"
