name: Create Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  create-release-with-assets:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            asset_name: diffdirs-linux-amd64-neovim-0-10.so
            ext: so
          - target: x86_64-apple-darwin
            os: macos-latest
            asset_name: diffdirs-darwin-amd64-neovim-0-10.so
            ext: dylib
          - target: aarch64-apple-darwin
            os: macos-latest
            asset_name: diffdirs-darwin-arm64-neovim-0-10.so
            ext: dylib
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Ensure toolchain
        run: rustup target add ${{ matrix.target }}
      - name: Build
        working-directory: ${{ github.workspace }}
        run: cargo build --target ${{ matrix.target }} --release && mv target/${{ matrix.target }}/release/libdiffdirs.${{ matrix.ext }} ${{ matrix.asset_name }}
      - uses: softprops/action-gh-release@v2
        working-directory: ${{ github.workspace }}
        with:
          draft: true
          files: ${{ matrix.asset_name }}
