name: Create Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  create-release-with-assets:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            asset_name: diffdirs-linux-amd64-neovim-0-10.so
          - target: x86_64-apple-darwin
            os: macos-latest
            asset_name: diffdirs-darwin-amd64-neovim-0-10.so
          - target: aarch64-apple-darwin
            os: macos-latest
            asset_name: diffdirs-darwin-arm64-neovim-0-10.so
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --target ${{ matrix.target }} --release && mv target/release/libdiffdirs* target/release/${{ matrix.asset_name }}
      - uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: target/release/${{ matrix.asset_name }}
