name: Create Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.release.outputs.id }}
    steps:
      - uses: softprops/action-gh-release@v2
        id: release
        with:
          draft: true
  update-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            asset_name: diffdirs-linux-x86_64-neovim-0-10.so
            ext: so
          - target: x86_64-apple-darwin
            os: macos-latest
            asset_name: diffdirs-darwin-x86_64-neovim-0-10.so
            ext: dylib
          - target: aarch64-apple-darwin
            os: macos-latest
            asset_name: diffdirs-darwin-arm64-neovim-0-10.so
            ext: dylib
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Ensure toolchain
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --target ${{ matrix.target }} --release && mv target/${{ matrix.target }}/release/libdiffdirs.${{ matrix.ext }} ${{ matrix.asset_name }}
      - name: Upload asset
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('node:fs');
            const data = fs.readFileSync("${{ matrix.asset_name }}");
            const repo_info = "${{ github.repository }}".split("/")
            github.rest.repos.uploadReleaseAsset({
              owner: repo_info[0],
              repo: repo_info[1],
              release_id: ${{ needs.create-release.outputs.release_id }},
              name: "${{ matrix.asset_name }}",
              data: data
            });
